import type { Metadata } from "next";
import localFont from "next/font/local";
import { Josefin_Sans, Merriweather } from 'next/font/google';
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
const joseSans = Josefin_Sans({
  subsets: ['latin'],
  display: 'swap',
  variable: "--font-jose-sans"
})
const merriWeather = Merriweather({
  subsets: ['latin'],
  display: 'swap',
  weight: "700", 
  variable: "--font-merri-weather"
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${merriWeather.variable} ${joseSans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
